### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dellaert** [sdrelton/perfprof#1]
Samuel,
I would love to use your script in benchmarking some solvers in [GTSAM](gtsam.org), a BSD-licensed library, but your repo has no license associated with. Would you consider adding a non-restrictive license like MIT or BSD? It's super-easy:
https://stackoverflow.com/questions/31639059/how-to-add-license-to-an-existing-github-project
PS, GPL would make this impossible, as it implies we would have to change GTSAM to GPL, as well
Frank

**Comment by sdrelton** [comment]
Hi Frank,

Sure I'll add a BSD license when I'm next at home.

Thanks for the heads up!

Cheers,
Sam

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sdrelton** [comment]
@dellaert Hey Frank, BSD-3 license ready to go.

Hope you find it useful - GTSAM looks really interesting!

Cheers,
Sam

**Comment by dellaert** [comment]
Thanks!!!!
